#ifndef ARGUMENTSPARSER_GLOBAL_H
#define ARGUMENTSPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ARGUMENTSPARSER_LIBRARY)
#  define ARGUMENTSPARSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ARGUMENTSPARSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ARGUMENTSPARSER_GLOBAL_H
